# Generated by Django 6.1.1 on 2026-09-14 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(allow_unicode=True, max_length=130, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('guests_allowed', models.BooleanField(default=False, help_text='Si activé, les comptes invités peuvent accéder à cette communauté.', verbose_name='Accès invités autorisé')),
                ('call_type', models.CharField(choices=[('none', 'Désactivé'), ('voice', 'Appel vocal'), ('video', 'Appel vidéo')], default='none', max_length=10, verbose_name='Type d’appel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
            ],
            options={
                'verbose_name': 'Communauté',
                'verbose_name_plural': 'Communautés',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4000, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communities.community')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Membre'), ('sub_admin', 'Sous-admin')], default='member', max_length=15, verbose_name='Rôle')),
                ('can_manage_members', models.BooleanField(default=False, verbose_name='Gérer les membres')),
                ('can_moderate', models.BooleanField(default=False, verbose_name='Modérer les messages')),
                ('can_edit_community', models.BooleanField(default=False, verbose_name='Modifier la communauté')),
                ('can_ban_users', models.BooleanField(default=False, verbose_name='Bannir des utilisateurs')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Rejoint le')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='communities.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adhésion',
                'verbose_name_plural': 'Adhésions',
                'unique_together': {('user', 'community')},
            },
        ),
    ]
