# Generated by Django 6.1.1 on 2026-09-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='can_launch_calls',
            field=models.BooleanField(default=False, verbose_name='Lancer les appels'),
        ),
    ]
