# Generated by Django 6.1.1 on 2026-09-15 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_membership_can_launch_calls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='call_type',
        ),
        migrations.CreateModel(
            name='CommunityCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('voice', 'Appel vocal'), ('video', 'Appel vidéo')], default='voice', max_length=10, verbose_name='Type')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Lancé le')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='communities.community', verbose_name='Communauté')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_calls', to=settings.AUTH_USER_MODEL, verbose_name='Lancé par')),
            ],
            options={
                'verbose_name': 'Appel en cours',
                'verbose_name_plural': 'Appels en cours',
                'ordering': ['-started_at'],
            },
        ),
    ]
