# Generated by Django 6.1.1 on 2026-09-16 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_remove_community_call_type_communitycall'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_support',
            field=models.BooleanField(default=False, help_text='Communauté spéciale où les invités et inscrits contactent les administrateurs.', verbose_name='Communauté d’assistance'),
        ),
        migrations.CreateModel(
            name='SupportThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('closed', 'Fermée')], default='open', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_support_threads', to=settings.AUTH_USER_MODEL, verbose_name='Admin choisi')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_threads', to='communities.community', verbose_name='Communauté')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_threads', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
            ],
            options={
                'verbose_name': 'Demande d’assistance',
                'verbose_name_plural': 'Demandes d’assistance',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4000, verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, help_text='Marqué lu quand l’autre partie ouvre la conversation.', verbose_name='Lu par le destinataire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communities.supportthread', verbose_name='Discussion')),
            ],
            options={
                'verbose_name': 'Message d’assistance',
                'verbose_name_plural': 'Messages d’assistance',
                'ordering': ['created_at'],
            },
        ),
    ]
