# Generated by Django 6.1.1 on 2026-09-18 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_support_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=64, verbose_name='Émetteur')),
                ('target', models.CharField(blank=True, max_length=64, verbose_name='Destinataire')),
                ('kind', models.CharField(choices=[('join', 'Rejoint'), ('offer', 'Offre'), ('answer', 'Réponse'), ('ice', 'Candidat ICE'), ('bye', 'Départ')], max_length=10, verbose_name='Type')),
                ('data', models.TextField(blank=True, verbose_name='Données')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='communities.communitycall', verbose_name='Appel')),
            ],
            options={
                'verbose_name': 'Signal d’appel',
                'verbose_name_plural': 'Signaux d’appel',
                'ordering': ['id'],
            },
        ),
    ]
