# Generated by Django 6.1.1 on 2026-09-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0008_call_signals'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='admins_only',
            field=models.BooleanField(default=False, help_text='Si activé, seuls les administrateurs du site peuvent voir et rejoindre cette communauté.', verbose_name='Réservée aux administrateurs'),
        ),
    ]
