# Generated by Django 6.1.1 on 2026-09-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_community_admins_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='can_manage_subadmins',
            field=models.BooleanField(default=False, verbose_name='Gérer les sous-admins'),
        ),
    ]
