# Generated by Django 6.1.1 on 2026-09-19 07:49

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_guest_duplicate_pseudo'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=40, unique=True, validators=[accounts.models.validate_username_global], verbose_name='Pseudo'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_guest', False)), fields=('username',), name='accounts_user_username_unique_non_guest'),
        ),
    ]
